name: side_header_list_view
description: ListView with sticky headers on the side. Inspired by the Android contacts app and the calendar app.
version: 0.0.4
author: Rene Floor <pub@renefloor.nl>
homepage: https://github.com/renefloor/side_header_list_view

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  meta: "^1.1.6"


dev_dependencies:
